### ISSUE TITLE
[Discussion] Should water, clean water, and mineral water still freeze?

### ISSUE THREAD

**Issue by chaosvolt** [Poragon/No-Freeze#1]
I figured I'd bring this up due to recent changes. As of https://github.com/CleverRaven/Cataclysm-DDA/pull/25809 the water in toilets becomes inaccessible when frozen. In most cases this isn't a problem as early spring is supposed to be above freezing during certain parts of the day, but it might be a tad tedious for some players.

Plus it causes potential "I died because I couldn't do X like I could in reality" situations in the few cases were toilet water is both necessary for survival and completely inaccessible. At least until being able to chisel away ice, attempt to directly heat up toilets, and/or smash it open and dump the ice into a large enough (likely non-resealable) container become options.

Labeling this discussion as, while it's not a big issue, I can still see multiple reasons why it might be acceptable to make water non-freezing:
1. Consistency as all other drinks can't freeze.
2. Removing the tedium of defrosting something that you'll likely consume at least as often as food (extra keypresses for minimal gameplay enhancement being one of two major reasons to use this mod).
3. Avoiding the potential recurrence of bugs related to water freezing in vehicle tanks, standing tanks, etc.

**Comment by Poragon** [comment]
I see no issue with making water freeze for consistencies sake, as well as supporting the purpose of the mod which is to remove the freezing mechanic for those who find it annoying in the first place. I'll add in water freezing as a separate file, so those who want to keep water freeze can just delete it.

**Comment by Poragon** [comment]
Solved by v1.04 c:

**Comment by chaosvolt** [comment]
Nice. :3
